name: cargo_dephell

# Why `on: repository_dispatch`?
#
# If we trigger this action on pull_request events,
# then it will run with the forked repo GITHUB_TOKEN
# this is a problem as it won't allow the action to write
# a comment on the PR in the last step.
#
# instead, we trigger this remotely via a bot we're running ourselves.
on:
  repository_dispatch:
    types: [new_PR]

jobs:
  run_cargo_dephell:
    runs-on: ubuntu-latest

    steps:
      - name: Who triggered this?
        env:
          PULL_ID: ${{ github.event.client_payload.pull_id }}
        run: |
          echo "action triggerd by https://github.com/diem/diem/pull/$PULL_ID"

      - name: Checkout master
        if: success()
        uses: actions/checkout@v2
        with:
          path: "master"
          fetch-depth: 1 # this is to make sure we obtain the target base commit
          repository: diem/diem # repo of the forked diem/diem
          ref: master # commit that triggered the PR

      - name: Checkout the PR
        if: success()
        uses: actions/checkout@v2
        with:
          path: "libra"
          fetch-depth: 50 # this is to make sure we obtain the target base commit
          repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }} # repo of the forked diem/diem
          ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR

      - name: diff
        run: |
          set -x
          set -e

          cd master
          ls
          ls ../ 
          ls ../libra
          output="$(cargo x diff-summary target/summaries/summary-release.toml ../libra/summaries/summary-release.toml)"
          cd -
          echo "${output}"

          # get download URLs
          DEP_NAME="cargo-dephell"
          VERSION="0.1.0"
          RESULT1=$(curl "https://crates.io/api/v1/crates/$NAME" | jq '.versions[] | select(.num == "'"$VERSION"'") | .dl_path')

          # get code
          mkdir images
          cd images
          wget "https://crates.io$RESULT1" -O crate1.tar.gz
          mkdir out1
          tar -xvf crate1.tar.gz -C out1

          # html diff
          npm install -g diff2html-cli
          git diff -u out1 out2 | diff2html -s line -F report.html -d word -i stdin

      - name: upload html report
        uses: actions/upload-artifact@v2
        with:
          name: depdiff
          path: report.html
